Create chatspace view
dddisk/chat-space pull request #4
Opened 2016-12-22 10:41 UTC by dddisk

create mark up

2016-12-22 10:46 UTC, dddisk commented
https://gyazo.com/34073b2c1efeb291cef4870cd24293ba

2016-12-23 00:12 UTC, hc0208 requested changes

2016-12-23 00:12 UTC, hc070208 commented on app/assets/stylesheets/messages.scss
> +  .chat-side {
&-sideみたいな書き方できるから他の部分もこういう感じで直そう。

2016-12-23 00:12 UTC, hc070208 commented on app/assets/stylesheets/messages.scss
> +  background-color: #38aef0;
#38aef0色は定数で管理しよう。

2016-12-23 06:47 UTC, hc070208 commented on app/assets/stylesheets/messages.scss
> +$sky-blue: #38aef0;
他の色もこういう感じにして欲しい！
よく使うやつでいいから

2016-12-24 04:58 UTC, hc070208 commented
LGTM

2016-12-24 10:09 UTC, merged